//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignForm
    {
        public int CampaignFormID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> AgentID { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<int> PurchaseID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Discount Discount { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
